{
 "title": "RSAPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Probe map.railway-stations.org",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"https://map.railway-stations.org\"}"
    }
   ]
  },
  {
   "title": "Probe api.railway-stations.org",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"https://api.railway-stations.org\"}"
    }
   ]
  },
  {
   "title": "Probe cloud.railway-stations.org",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"https://cloud.railway-stations.org\"}"
    }
   ]
  }
 ]
}