all:
  hosts:
    h2945676: 
      ansible_host: railway-stations.org 
    h2951065: 
      ansible_host: h2951065.stratoserver.net
      monitoring_target: railway-stations.org
  vars:
      ansible_python_interpreter: /usr/bin/python3
  children:
    railwaystations:
      hosts:
        h2945676:
    monitoring:
      hosts:
        h2951065:
    prod:
      hosts:
        h2945676:
        h2951065:
    debian:
      hosts:
        h2945676:
        h2951065:
