---
- hosts: monitoring
  roles:
    - cloudalchemy.prometheus
    - cloudalchemy.grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - 192.168.0.229:9100
    grafana_security:
      admin_user: admin
      admin_password: admin
    grafana_datasources:
      - name: prometheus
        type: Prometheus
        access: proxy
        url: 'http://127.0.0.1:9090'
        basicAuth: false
    grafana_dashboards:
      - dashboard_id: 3662
        revision_id: 2
        datasource: prometheus
    grafana_dashboards:
      - dashboard_id: 13978
        revision_id: 1
        datasource: prometheus
        

- hosts: webserver
  roles:
    - cloudalchemy.node_exporter        
  vars:
    node_exporter_web_listen_address: '127.0.0.1:9100'
