---
- hosts: monitoring
  vars_files:
    - vars/secret-vars.yml
    - defaults/main.yml
  roles:
    - docker
    - monitoring

- hosts: railwaystations
  vars_files:
    - vars/secret-vars.yml
    - defaults/main.yml
  roles:
    - exporters
