---
- hosts: monitoring
  vars_files:
    - vars/secret-vars.yml
    - defaults/main.yml
  vars:
    - admin_password: "{{ vault_admin_password }}"
    - admin_password_hash: "{{ vault_admin_password_hash }}"
  roles:
    - docker
    - monitoring

- hosts: railwaystations
  vars_files:
    - vars/secret-vars.yml
    - defaults/main.yml
  roles:
    - exporters
