version: '2.1'

services:

  rsapi:
    image: railwaystations/rsapi@sha256:4c9e15d0341fd50ea300585cbd22e59b2d97b7d023ca61ad8b1583fecf3e7875
    container_name: rsapi
    volumes:
      - /var/rsapi:/var/rsapi
      - /var/www/fotos:/var/rsapi/photos
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
# using network_mode host, exposing ports has no effect
#    ports:
#      - "localhost:8080:8080"
#      - "localhost:8081:8081"
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
