version: '2.1'

services:

  rsapi:
    image: railwaystations/rsapi@sha256:d526a93b5ff595da6915668308d47fa79c6bbf9c6f158ca8079ffae63879d29d
    container_name: rsapi
    volumes:
      - /var/rsapi:/var/rsapi
      - /var/www/fotos:/var/rsapi/photos
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
# using network_mode host, exposing ports has no effect
#    ports:
#      - "localhost:8080:8080"
#      - "localhost:8081:8081"
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
