version: '2.1'

services:

  rsapi:
    image: railwaystations/rsapi@sha256:f31ee87f9d4ac977196b41569913a6e88d0074da8b186616e332033fe65af454
    container_name: rsapi
    volumes:
      - /var/rsapi:/var/rsapi
      - /var/www/fotos:/var/rsapi/photos
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
# using network_mode host, exposing ports has no effect
#    ports:
#      - "localhost:8080:8080"
#      - "localhost:8081:8081"
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
