version: '2.1'

services:

  rsapi:
    image: railwaystations/rsapi@sha256:257a4b9bd64ca1c0fad8972f64ae457d5ad9cb87099b6d2fda2e1424aaacbeca
    container_name: rsapi
    volumes:
      - /var/rsapi:/var/rsapi
      - /var/www/fotos:/var/rsapi/photos
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
# using network_mode host, exposing ports has no effect
#    ports:
#      - "localhost:8080:8080"
#      - "localhost:8081:8081"
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
