version: '2.1'

services:

  rsapi:
    image: railwaystations/rsapi@sha256:4fcd54c152136dd9a04a8ebe15796b1ab72a1c05165a17acbf1b7cfb01762d2f
    container_name: rsapi
    volumes:
      - /var/rsapi:/var/rsapi
      - /var/www/fotos:/var/rsapi/photos
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
# using network_mode host, exposing ports has no effect
#    ports:
#      - "localhost:8080:8080"
#      - "localhost:8081:8081"
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
