---
- name: create rsapi directory
  become: true
  file:
    path: "{{ rsapi_dir }}"
    state: directory
    mode: 0755

- name: rsapi config
  become: true
  template:
    src: "application-prod.yaml.j2"
    dest: "{{ rsapi_dir }}/application-prod.yaml"

- name: compose file
  become: true
  ansible.builtin.copy:
    src: "./files/docker-compose.yml"
    dest: "{{ rsapi_dir }}/"

- name: access_log file
  become: true
  ansible.builtin.copy:
    src: "./files/access_log.sh"
    dest: "{{ rsapi_dir }}/"

- name: Ensure group "rsapi" exists
  become: true
  ansible.builtin.group:
    name: rsapi
    state: present

- name: Add the user 'rsapi' to group 'rsapi'
  become: true
  ansible.builtin.user:
    name: rsapi
    shell: /usr/sbin/nologin
    comment: Railway-Stations API user
    group: rsapi    

- name: Run `docker-compose up`
  become: true
  community.docker.docker_compose:
    project_src: "{{ rsapi_dir }}"
    build: no
    pull: true
    recreate: always
