---
- name: Install dependencies
  become: true
  apt:
    name: 
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - libffi-dev
    state: present

- name: Add Docker's public GPG key to the APT keyring
  become: true
  apt_key:
    id: "{{ docker__apt_key_id }}"
    url: "{{ docker__apt_key_url }}"

- name: Configure Docker's upstream APT repository
  become: true
  apt_repository:
    repo: "{{ docker__apt_repository }}"
    update_cache: true

- name: Install docker
  become: true
  apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: Install docker-compose python package
  become: true
  pip:
    name: docker-compose

- name: Add user(s) to "docker" group
  become: true
  user:
    name: "{{ item }}"
    groups: "docker"
    append: true
  loop: "{{ docker__users }}"    
